vich_uploader:
    db_driver: orm

    mappings:
        profilPicture:
            uri_prefix: /IMAGES/profilPicture
            upload_destination: '%kernel.project_dir%/public/IMAGES/profilPicture'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
